# Generated by Django 5.0.1 on 2024-02-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbt_app', '0002_delete_sake_item_alter_task_datetime_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='sake_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('maker_name', models.CharField(max_length=50)),
                ('class_type', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=20)),
                ('volume', models.IntegerField()),
                ('jp_code', models.IntegerField()),
                ('it_code', models.IntegerField()),
                ('comment', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.IntegerField()),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
