# Generated by Django 5.0.1 on 2025-06-05 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbt_app', '0005_alter_task_datetime_limit_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('mail_contact', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('billing_name', models.CharField(max_length=50)),
                ('billing_address', models.CharField(max_length=100)),
                ('piva', models.CharField(max_length=20)),
                ('cf', models.CharField(max_length=20)),
                ('pec', models.EmailField(max_length=254)),
                ('codice_univoco', models.CharField(max_length=10)),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbt_app.customer'),
        ),
    ]
