# Generated by Django 5.0.1 on 2025-06-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbt_app', '0008_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default=' ', max_length=5),
        ),
    ]
