# Generated by Django 5.0.1 on 2025-12-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbt_app', '0009_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sake_item',
            name='fullname',
            field=models.CharField(default='fullname', max_length=180),
        ),
    ]
