# Generated by Django 5.0.1 on 2025-12-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbt_app', '0010_sake_item_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contents',
            field=models.CharField(default='Aggiungi qualcosa a questo ordine', max_length=1000),
        ),
    ]
