# Generated by Django 5.0.1 on 2025-12-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbt_app', '0012_order_item_order_price_order_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='sake_item',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
    ]
