# Generated by Django 5.0.1 on 2025-12-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbt_app', '0013_sake_item_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sake_item',
            name='alcol',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
