# Generated by Django 5.0.1 on 2025-12-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbt_app', '0016_remove_sake_item_koji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sake_item',
            name='seimai',
        ),
    ]
